Arduino: add missing header files
This fixes the error:

$ BOARD=arduino-mega2560 make -C tests/pkg_arduino_sdi_12/
[...]
[...]RIOT/build/pkg/arduino_sdi_12/src/SDI12.h:131:10: fatal error: Stream.h: No such file or directory