gnrc_icmpv6_error: use dispatch_send() instead of send()
This way other threads than `gnrc_ipv6`'s event handling thread can
receive these packages (good for debugging and testing ;-)).