drivers/sht2x: fix missing kernel_defines.h include
Fix:
drivers/sht2x/include/sht2x_params.h:134:50: error: missing binary
operator before token "("

    Signed-off-by: Gilles DOFFE <g.doffe@gmail.com>