Arduino: add missing cpp files
This fixes the linker errors:

$ BOARD=arduino-mega2560 make -C tests/pkg_arduino_sdi_12/
[...]
[...]/RIOT/tests/pkg_arduino_sdi_12/bin/arduino-mega2560/arduino_sdi_12/SDI12.o:(.rodata._ZTV5SDI12[_ZTV5SDI12]+0x6): undefined reference to `_ZN5Print5writeEPKhj'