drivers/ng_at86rf2xx: correct array bounds on tx_pow_to_dbm
There are only 37 entries in the array in the C file as well as in the
table in the data sheet.

Fixes the following cppcheck error:

    drivers/ng_at86rf2xx/ng_at86rf2xx_getset.c:49: error (arrayIndexOutOfBounds): Array 'dbm_to_tx_pow_868[37]' accessed at index 37, which is out of bounds.