tests/pkg_tiny-asn1: blacklist wsn430 boards
Boards do not have enough memory to `malloc` for the test

    ERROR: Could not allocate the memory for the ASN.1 objects

(cherry picked from commit a1fe556f0215b2073886bf58f20604ca0f2be630)