sock: make queue_array parameter a pointer
Since sock_tcp_t isn't defined at this moment (only declared) the
compiler is complaining about the use of an array in the parameter list
here.

    sys/include/net/sock/tcp.h:119:32: error: array type has incomplete element type ‘sock_tcp_t {aka struct
sock_tcp}’
                         sock_tcp_t queue_array[], unsigned queue_len,
                                    ^