drivers/hm330x: fix missing kernel_defines.h include
Fix:
drivers/include/hm330x.h:66:12: error: missing binary operator before
token "("

Signed-off-by: Gilles DOFFE <g.doffe@gmail.com>