Define F_CPU, required by Arduino-SDI-12 package
This fixes the following error:

$ BOARD=arduino-mega2560 make -C tests/pkg_arduino_sdi_12/
[...]
[...]/RIOT/build/pkg/arduino_sdi_12/src/SDI12_boards.cpp:35:16: error: ‘preSDI12_TCCR2B’ defined but not used [-Werror=unused-variable]
   35 | static uint8_t preSDI12_TCCR2B;